version: '3.3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress 
    volumes:
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./conf/wordpress/.htaccess:/var/www/html/.htaccess
    depends_on:
      - mariadb
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress  
      WORDPRESS_DB_PORT: 3306  
      WORDPRESS_TABLE_PREFIX: 'wp_'
      WORDPRESS_DEBUG: 1
      WP_HOME: https://wordpress.local
      WP_SITEURL: https://wordpress.local
    restart: on-failure

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  wp_data:
